astropy/astrowidgets

astrowidgets/core.py
astrowidgets/tests/test_api.py

This implements the idea I was suggesting in #9

Zoom updates

---

appveyor.yml

Fix #24 
If test passed, I am just going to merge it since this should be uncontroversial...

TST: Enable Appveyor

---

.travis.yml
astrowidgets/core.py
setup.cfg

Fix #20 
Also remove incantation to allow it to fail. PEP8 everything!

TST: Replace pycodestyle with flake8

---

example_notebooks/ginga_widget.ipynb

This solution is from astropy/astropy#7757.

Widget notebook: CCDData should use cache

---

astrowidgets/_astropy_init.py
astrowidgets/core.py
astrowidgets/tests/test_image_wdiget.py

This fixes #45 (the problem that add_markers modifies the input table).

Fix add_markers

---

astrowidgets/core.py
astrowidgets/tests/test_image_wdiget.py

This fixes #47 by adding a pixel_coords_offset to the initializer and using it wherever the offset comes up.
I can add a property/setter if desired.
I did sneak in one other change: value is now displayed to three decimal pplaces

Add pixel_coords_offset attribute

---

astrowidgets/tests/test_api.py

Hi! I finished the test_reset_marks. Also I am wondering is it better to accumulate more changes before open a pull request?

finished test_reset_marks

---

astrowidgets/core.py
astrowidgets/tests/test_api.py
example_notebooks/ginga_widget.ipynb

Hi! the test are added in the function "test_set_markers", and comment are changed. Thank you!

added point shape for markdown

---

astrowidgets/core.py
astrowidgets/tests/test_api.py
astrowidgets/tests/test_image_widget.py
example_notebooks/ginga_widget.ipynb
example_notebooks/gui_interactions.ipynb
example_notebooks/named_markers.ipynb

This started as a refactor of the marking interface, and does fix #16, but ended up also implementing the remaining parts of the API that hadn't been implemented yet. 
A little bit of documentation and we would be ready for an alpha release, I think?

Implement the remaining API for the ginga viewer

---

example_notebooks/ginga_widget.ipynb
example_notebooks/gui_interactions.ipynb
example_notebooks/named_markers.ipynb

Fix data URLs

---

.travis.yml
README.rst
docs/astrowidgets/api.rst
docs/astrowidgets/index.rst
docs/conf.py
docs/index.rst
docs/install.rst
setup.cfg

This is nowhere near complete but better than it was....

Add some docs

---

astrowidgets/core.py
astrowidgets/tests/test_image_widget.py

Thanks to @isobelsnellenberger for finding this bug...

Add test and fix for case of adding single SkyCoord marker

---

astrowidgets/conftest.py
docs/conf.py

MNT: Clean up of conf.py and conftest.py

---

.github/workflows/publish.yml
setup.cfg

MNT: Auto publish to PyPI

---

.readthedocs.yml
docs/requirements.txt

Update RTD config to reflect how we would build the docs locally.

DOC: Update RTD config

---

astrowidgets/core.py

MNT: Compatibility with Ginga 4.0.dev

---

.github/workflows/ci_workflows.yml
.github/workflows/predeps_workflow.yml
.github/workflows/publish.yml
docs/install.rst
setup.cfg
tox.ini

Fix CI workflows, update publish workflow, add RC testing workflow.
If I cannot get this to work with tox 4, I am also going to pin `tox<4`, let's see...

TST: Fix workflows, add RC testing

---

.github/workflows/ci_workflows.yml
.readthedocs.yml
astrowidgets/interface_definition.py
setup.cfg

Pretty sure I did this right, but this is my first genuine attempt at type hinting, so 🤷‍♂️ 
Related to #167

Add type hints to methods of interface, including arguments

---

astrowidgets/ginga.py
astrowidgets/interface_definition.py

This addresses [the comment in #170](https://github.com/astropy/astrowidgets/pull/170#discussion_r1254556606) about adding more detail in the docstring about typing. I did it two different ways, not sure which is the correct one to use....

Better document type options

---

setup.cfg

Remove a bunch of pytest warning filters

---

astrowidgets/bqplot.py
astrowidgets/tests/test_widget_api_bqplot.py

Some flake8 issues were ignored when #191 was merged....this fixes those issues.

Fix flake8 issues
