astropy/astrowidgets

README.rst
astrowidgets/__init__.py
docs/astrowidgets/index.rst
docs/index.rst
setup.cfg

DOC: Setup doc layout, add installation notes

---

.travis.yml
appveyor.yml
astrowidgets/core.py
docs/astrowidgets/index.rst
docs/index.rst

Fix #31 
Also moved dev notes to https://github.com/astropy/astrowidgets/wiki/DevNotes and added link to example notebook to docs.

Optional opencv

---

astrowidgets/core.py
astrowidgets/tests/test_api.py
astrowidgets/tests/test_image_wdiget.py

This is an alternative to #14. 
There are really two sizes here:
+ The width/height of the image
+ The width/height of the ipywidgets Box containing the image and the cursor display. 
I guessing most users will care more about the *image* size; to make explicit that that is what is settable I've changed the names to `image_width` and `image_height`. 
Ideally those would be set to the width/height of the *layout* of the image widget rather than the image itself. The reason is that any css that applies to the image will override the img width/height tags. That means, for example, that setting the width of the `ipywidgets.Vbox` using the `layout` of the `VBox`, which applies the css width to everything in the box, will override the img width/height.
If we set width/height of the layout then …

Add properties for image width/height

---

example_notebooks/ginga_widget.ipynb

Turns out a couple of the open issues/notebook to-dos have already been fixed 😀. This just removes a couple of notes from the notebook and finishes up the slider-to-control-number-of-stars demo.
Fixes #37 
Fixes #38

Remove a couple of to-dos from the example notebook

---

astrowidgets/core.py
astrowidgets/tests/test_image_wdiget.py

This fixes #50 by internally converting SkyCoord markers to pixel coordinates. I'm not sure what makes adding markers with `coord_type='wcs'` so slow, but it is. Simply adding 1000 markers as WCS took 12 seconds before this PR, compared to 0.2 seconds for adding 1000 markers in pixel coordinates. 
Line profiles are below demonstrating where the slowdown was occurring. 
I also added a test that the internal conversion to pixels still gives the correct worl coordinates back via `get_markers`.

Speed up adding markers in world coordinates by 100x

---

astrowidgets/_astropy_init.py

This one-line change prevents pytest from picking up the test function as a test. See astropy/package-template#373.
*This is an automated fix by @pllim. If this is opened in error, please close without merge.*

Prevent pytest from picking up test function as a test

---

setup.cfg

The real work has been done in ipyevents; this simply sets a new lower bound for the version of that package.
One side effect of the changes is that the image widget now has a blue border around it when it has focus. I don't think that is a problem, but if we want to address we can by adding the appropriate styling (though I'd rather do that in a separate PR).
This fixes #44 and I think also mwcraig/ipyevents#27

Fix jupyter lab compatibility

---

astrowidgets/core.py
astrowidgets/tests/test_api.py

I implemented this for spacetelescope/dat_pyinthesky#7 because it was painful to cycle through colormaps interactively using arrow keys. With this, I can programmatically set the colormap I want.

Expose methods for colormap

---

docs/index.rst

To update installation instruction with a modified command, plus to add a note to accompany it to warn users to check and use the appropriate pip version to install astrowidgets...

Update installation instruction and notes on "index.rst"

---

astrowidgets/core.py

As it happens the `value` if the `Image` widget is bytes in PNG format so we just need to write it out. This also makes the save independent of ginga.

Simplify saving image view as PNG

---

.travis.yml
appveyor.yml
astrowidgets/conftest.py
docs/conf.py
setup.cfg
setup.py

* Fix #83 by adding Ginga dev to Astropy dev job.
* Follow the lead of astropy/astropy#8891 and remove Numpy pre-release job. Any breakage caused by unreleased Numpy will be likely caught upstream first anyway. 🤞 
* Remove warnings from setup process.
* Update Appveyor to pip install Ginga (could not find in `conda`) and use Python 3.7.
* Improve pytest header to report dependency versions that we care about.

ENH: Update CI matrix

---

astrowidgets/core.py
example_notebooks/named_markers.ipynb

This does two things:
+ Report the names of the markers in the table returned by `get_markers`
+ Use the name passed in to `start_marking`

A couple little fixes for marker names

---

astrowidgets/tests/test_api.py

`pytest` 5 changed the raised error API a little.

Fix pytest 5 compatibility

---

astrowidgets/core.py
astrowidgets/tests/test_api.py
astrowidgets/tests/test_image_widget.py
setup.cfg

This fixes #97 by handling these cases:
+ User asks for a marker name that the image widget does not know about (raises a `ValueError`)
+ User asks for a marker name which the widget knows about but has no markers in it (raise a `RuntimeWarning` with a clear message)
+ User asks for all markers and one of the marker sets has no markers in it (don't crash, just ignore the empty marker set).

Fix some edge cases in using named marker sets

---

.travis.yml

My best guess is that the issue is a solve that is timing out. To get to that job quickly it is temporarily added to the initial tests.

Fix failing travis job

---

.travis.yml
example_notebooks/ginga_wcsaxes.ipynb

Not sure if you want to merge this or not but I got it to work. Thanks to @ejeschke's foresight in the canvas drawing design, it was easier to port than I thought! Also see https://ginga.readthedocs.io/en/latest/manual/plugins_local/wcsaxes.html
Fix #79
cc @jdavies-st
**Example screenshot**
p.s. I didn't spend a lot of time to tweak the WCS axes layout parameters to make it perfect but it can be done.

ENH: Add example to draw WCS axes

---

astrowidgets/core.py

While working with #110, I found that invalid WCS causes the cursor info bar to not display at all, when the values raises `AssertionError` in Ginga. I find that it makes more sense to display info bar anyway without RA and Dec, when WCS conversion fails for whatever reason, instead to just not work.

Ignore RA/Dec string formatting failures

---

setup.cfg

TST: Stop ignoring warnings

---

astrowidgets/_astropy_init.py

This is probably leftover from package template. This package does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497

MNT: Remove unused astropy config code

---

astrowidgets/core.py
astrowidgets/tests/test_api.py
example_notebooks/ginga_widget.ipynb

Fix #139 
* New offset_by with new API
* Deprecate offset_to with old API.
* Added tests and updated example notebook.
* Bonus: Fixed a test that was writing file into source dir.

New offset_by with new API

---

.readthedocs.yml
astrowidgets/conftest.py
conftest.py

This pull request is to remove soon to be deprecated code; also see astropy/astropy#12633 .

MNT: Do not use enable_deprecations_as_exceptions

---

astrowidgets/core.py
setup.cfg

There was a bunch of API deprecated/removed for upcoming Ginga v4.0. One of those failed the devdeps job here. This will make the CI green again.
This PR also specifies a theoretical minversion for Ginga.

MNT: Compatibility with Ginga v4

---

setup.cfg

The warning had been resolved by test https://github.com/ejeschke/ginga/pull/1037

MNT: Un-ignore ioloop DeprecationWarning from Ginga

---

astrowidgets/core.py

- fix #159
- fixes test for "stretch"; use method API to fetch the distribution object rather than accessing instance variable

Fix test for stretch

---

astrowidgets/core.py

The use_opencv parameter has been deprecated in ginga; opencv will be used automatically if it is installed.

Deprecate use_opencv parameter

---

astrowidgets/ginga.py
astrowidgets/interface_definition.py
astrowidgets/tests/widget_api_test.py

I was discussing astrowidgets with a colleague who pointed out that, by default, `astrowidgets` silently overwrites files when it saves. This PR adds an `overwrite` argument to the `save` method and implements it in the ginga viewer. I'm hoping this is uncontroversial enough that it can be approveed/merged without a synchronous discussion 😀

Add overwrite argument to save method

---

.github/dependabot.yml
.github/workflows/ci_workflows.yml
.github/workflows/predeps_workflow.yml
.github/workflows/publish.yml
.readthedocs.yaml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed
